apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adp-documentation
  annotations:
    github.com/project-slug: DEFRA/adp-documentation
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://defra.github.io/adp-documentation
      title: ADP Public Github Page
      icon: dashboard
spec:
  type: documentation
  lifecycle: experimental
  owner: ADP
