site_name: Defra's ADP Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  favicon: images/favicon.png
  logo: images/favicon.png
  language: en
extra: 
  version: 0.0.1
  last_updated: 2024-01-28
  repo_url: https://github.com/defra/adp-documentation
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/defra/adp-documentation
  generator: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid_custom
  - tables
  - attr_list
  - md_in_html

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/loader.js

copyright: |
  &copy; 2024 <a href="https://defra.github.io/"  target="_blank" rel="noopener">Defra</a>

plugins:
  - search
  - mermaid2
  - mkdocs-nav-weight
  - techdocs-core

docs_dir: docs

#nav:
#- home: 
#  - about.md
#  - WhatsNext: index.md