site_name: DEFRA - ADP Documentation
theme:
  name: material
  palette:
    primary: black
    accent: light blue
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  favicon: images/favicon.png
  logo: images/favicon.png
  language: en
extra: 
  version: 0.0.1
  last_updated: 2024-02-19
  repo_url: https://github.com/defra/adp-documentation
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/defra/adp-documentation
  generator: false

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #- pymdownx.extra:
  #    pymdownx.superfences:
  #      custom_fences:
  #        - name: mermaid
  #          class: mermaid
  #          format: !!python/name:mermaid2.fence_mermaid_custom

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/loader.js

copyright: |
  &copy; Crown copyright | <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"  target="_blank" rel="noopener">All content is available under the Open Government Licence v3.0</a>

plugins:
  - search
  #- mermaid2
  - mkdocs-nav-weight
  - techdocs-core

docs_dir: docs

#page tree e.g. https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
nav:
  - Why ADP: index.md
  - Getting Started:
    - Onboarding a user: Getting-Started/onboarding-a-user.md
    - Onboarding a delivery project: Getting-Started/onboarding-a-delivery-project.md
    - Onboarding a delivery programme: Getting-Started/onboarding-a-delivery-programme.md
  - How to guides:
    - How to create a platform service: How-to-guides/how-to-create-a-platform-service.md
  - Migrate to ADP:
    - Migrate a delivery project: Migrate-to-ADP/migrate-a-delivery-project.md
    - Migrate platform service: Migrate-to-ADP/migrate-a-platform-service.md
    - Migrate production data: Migrate-to-ADP/migrate-production-data.md
  - Platform Strategy:
    - Documentation Approach: Platform-Strategy/documentation-approach.md
  - Platform Architecture:
    - Architecture Overview: Platform-Architecture/architecture-overview.md
    - Environments: Platform-Architecture/environments.md
    - Tech Radar: Platform-Architecture/tech-radar.md
    - Scaling: Platform-Architecture/scaling.md
    - Integration Patterns:
      - Overview: Platform-Architecture/integration-patterns/overview.md
      - Dynamics & Plower Platform: Platform-Architecture/integration-patterns/dynamics-and-platform-platform.md
    - Architectural Components:
      - Istio Service Mesh POC: Platform-Architecture/architectural-components/istio-service-mesh-poc.md
      - Application Hosting: Platform-Architecture/architectural-components/application-hosting.md
      - Microservices & AKS: Platform-Architecture/architectural-components/microservices-and-aks.md
      - Secrets & Configuration: Platform-Architecture/architectural-components/secrets-and-configuration.md
      - monitoring:
        - Overview: Platform-Architecture/architectural-components/monitoring/overview.md
        - Automated Monitoring Implementation: Platform-Architecture/architectural-components/monitoring/automated-monitoring-implementation.md
        - Network Watcher: Platform-Architecture/architectural-components/monitoring/network-watcher.md
        - Alerts: Platform-Architecture/architectural-components/monitoring/alerts.md
      - CI, CD, & Automation:
        - GitOps for AKS:
          - Overview: Platform-Architecture/architectural-components/ci-cd-and-automation/gitops-for-aks/overview.md
        - Azure Service Operator for AKS: Platform-Architecture/architectural-components/ci-cd-and-automation/azure-service-operator-for-aks.md

  - Developer Reference:
    - ASO Helm Library Chart: Developer-Reference/Infrastructure/ASO Helm Library Chart.md
    - ADP Portal: Developer-Reference/Infrastructure/ADP Portal.md
    - Helm Library Memory & CPU Tiers: Developer-Reference/Infrastructure/helm-library-memory-and-cpu-tiers.md
    - Reference Applications:
      - FCP Demo Services:
        - Overview: Developer-Reference/reference-applications/fcp-demo-services/overview.md
